### ISSUE TITLE
Current state of this package

### ISSUE THREAD

**Issue by ararslan** [JuliaCloud/AWSAuth.jl#11]
If you're reading this, you might be thinking to yourself, "It really seems like this package saw a burst of activity then went out to the back yard to die." Fear not, this package is not abandoned, though both its current and planned functionality is currently available elsewhere.

## Functionality

- [x] AWS Signature v4 signing of `HTTP.Request`s. Note that this functionality is duplicated (modulo a slight renaming) from what's in HTTP.

- [x] AWS Signature v4 authentication layer for `Request`s, also duplicated from HTTP. Unless/until https://github.com/JuliaWeb/HTTP.jl/issues/389 is resolved, we will need #10, which pares the implemented functionality here down to just AWS4 signing, striking this item from the list.
- [x] AWS credentials. Sam O'Connor had mentioned that we could potentially move that functionality from AWSCore to this package, but nothing has happened yet on that front.

## Future work

Any interested party is welcome to contribute to this package's development. As far as I know, all of the functionality that has ever been discussed for this package is outlined above. That is not to say, however, that other functionality would not be useful! Ideally this package will eventually be a plug-and-play interface for authentication with the various AWS packages, but there is a ways yet to go for that, as you can see from the list here.

**Comment by mattBrzezinski** [comment]
Closing this issue as the functionality of this package is now in `AWSCore.jl`.
